name: 'Deploy prod'
description: 'Builds and deploys app to vercel'
inputs:
  vercel-token:
    required: true
    description: "Vercel token"
runs:
  using: 'composite'
  steps:
    - name: Install Vercel CLI
      run: pnpm install --global vercel@latest
      shell: bash

    - name: Pull Vercel Environment Information
      run: vercel pull --yes --environment=production --token=${{ inputs.vercel-token }}
      shell: bash

    - name: Build Project Artifacts
      run: vercel build --prod --token=${{ inputs.vercel-token }}
      shell: bash

    - name: Deploy Project Artifacts to Vercel
      run: vercel deploy --prebuilt --prod --token=${{ inputs.vercel-token }}
      shell: bash