name: 'Deploy preview'
description: 'Builds and deploys preview of app to vercel'
inputs:
  vercel-token:
    required: true
    description: "Vercel token"
runs:
  using: 'composite'
  steps:
    - name: Install Vercel CLI
      run: pnpm install --global vercel@latest
      shell: bash

    - name: Pull Vercel Environment Information
      run: vercel pull --yes --environment=preview --token=${{ inputs.vercel-token }}
      shell: bash

    - name: Build Project Artifacts
      run: vercel build --token=${{ inputs.vercel-token }}
      shell: bash

    - name: Deploy Project Artifacts to Vercel
      run: vercel deploy --prebuilt --token=${{ inputs.vercel-token }}
      shell: bash